### ISSUE TITLE
ERROR During Install MONAI Label #1801

### ISSUE THREAD

**Issue by VuDuc5** [Project-MONAI/MONAILabel#1802]
Hello, I am trying to install the MONAI Label and trying to download radiology app using the code " !monailabel apps --download --name radiology --output apps". I got this Problem:
"(Monai) C:\Users\user>monailabel apps --download --name radiology --output apps
Using PYTHONPATH=C:\Users\user\anaconda3\envs;
""
Traceback (most recent call last):
File "C:\Users\user\anaconda3\envs\Monai\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\user\anaconda3\envs\Monai\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\user\anaconda3\envs\Monai\lib\site-packages\monailabel\main.py", line 24, in
from monailabel.config import settings
File "C:\Users\user\anaconda3\envs\Monai\lib\site-packages\monailabel\config.py", line 23, in
class Settings(BaseSettings):
File "C:\Users\user\anaconda3\envs\Monai\lib\site-packages\monailabel\config.py", line 109, in Settings
if is_package_installed("SAM-2")
File "C:\Users\user\anaconda3\envs\Monai\lib\site-packages\monailabel\config.py", line 20, in is_package_installed
return name in sorted(x.name for x in distributions())
File "C:\Users\user\anaconda3\envs\Monai\lib\site-packages\monailabel\config.py", line 20, in
return name in sorted(x.name for x in distributions())
AttributeError: 'PathDistribution' object has no attribute 'name'"

Also, the AttributeError: 'PathDistribution' object has no attribute 'name'" happens when I try to start the MONAI server:
(Monai) C:\Users\user>monailabel start_server --app ChooseApp --studies path/dataset --conf model ChooseModel
Using PYTHONPATH=C:\Users\user\anaconda3\envs;
""
Traceback (most recent call last):
File "C:\Users\user\anaconda3\envs\Monai\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\user\anaconda3\envs\Monai\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\user\anaconda3\envs\Monai\lib\site-packages\monailabel\main.py", line 24, in
from monailabel.config import settings
File "C:\Users\user\anaconda3\envs\Monai\lib\site-packages\monailabel\config.py", line 23, in
class Settings(BaseSettings):
File "C:\Users\user\anaconda3\envs\Monai\lib\site-packages\monailabel\config.py", line 109, in Settings
if is_package_installed("SAM-2")
File "C:\Users\user\anaconda3\envs\Monai\lib\site-packages\monailabel\config.py", line 20, in is_package_installed
return name in sorted(x.name for x in distributions())
File "C:\Users\user\anaconda3\envs\Monai\lib\site-packages\monailabel\config.py", line 20, in
return name in sorted(x.name for x in distributions())
AttributeError: 'PathDistribution' object has no attribute 'name'

Could you please help me out ?. Thank you

**Comment by lassoan** [comment]
This was fixed in https://github.com/Project-MONAI/MONAILabel/commit/30e97b49ce02efd0e897c55f874b5c80bf27c7aa, please update your MONAILabel.

**Comment by soumen02** [comment]
Hi, I was still getting the same error with the latest version of monailabel (v0.8.5)

I was able to fix it by modifying the monailabel _config.py_ file in my environment. 

Update the below function to look like this. 

```
def is_package_installed(name):
    try:
        from importlib.metadata import distributions
        return name in [dist.metadata['Name'] for dist in distributions()]
    except:
        # Fallback method
        try:
            import pkg_resources
            pkg_resources.get_distribution(name)
            return True
        except:
            return False
```

Hope this helps.

**Comment by diazandr3s** [comment]
Closing this issue. Please reopen if the problem persists.
